# Generated by Django 5.0.4 on 2025-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_create_account_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignment',
            field=models.CharField(default='unassigned', max_length=100),
        ),
    ]
