# Generated by Django 5.2.5 on 2025-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_ticket_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
